name: keep-active-task

run-name: ${{ github.actor }} trigger workflow

on:
  schedule:
    - cron: "45 17 * * *"

jobs:
  keep-live-job:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Execute Workflow
        run: |
          git config --local user.name "${{ github.actor }}"
          git config --local user.email "wisdom.geeker@gmail.com"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          git commit --allow-empty -m "keep workflow active"
          git push
